# =============================================================================
#
# This file uses mise as the single source of truth for all development tasks.
# All hooks delegate to mise tasks to ensure consistency across development,
# CI/CD, and git hook workflows.
#
# To install lefthook: mise install
# To install hooks: lefthook install
# To run manually: lefthook run pre-commit
#
# =============================================================================

assert_lefthook_installed: true
colors: true
no_tty: false

pre-commit:
  parallel: true

  jobs:
    # TypeScript/JSON (Biome)
    - name: typescript:typecheck
      glob: "*.{ts,tsx}"
      run: mise run typescript:typecheck

    - name: biome:lint
      glob: "*.{ts,tsx,js,jsx,json}"
      run: mise run biome:lint:nofix

    # Markdown
    - name: markdown:lint
      glob: "*.md"
      run: mise run markdown:lint:nofix

    # TOML
    - name: toml:lint
      glob: "*.toml"
      run: mise run toml:lint:nofix

    # Shell
    - name: shell:lint
      glob: "*.sh"
      run: mise run shell:lint:fix

    # Go
    - name: go:format
      glob: "backend/**/*.go"
      run: mise run go:format:fix

    - name: go:lint
      glob: "backend/**/*.go"
      run: mise run go:lint:nofix
