[tools]
bun = "latest"
biome = "latest"
lefthook = "latest"
markdownlint-cli2 = "latest"
taplo = "latest"
usage = "latest"

[settings]
jobs = 24

# =============================================================================
# Development
# =============================================================================

[tasks.bun]
run = "bun"
description = "Run Bun"

# =============================================================================
# Installation & Setup
# =============================================================================

[tasks.install]
description = "Install dependencies"
run = "bun install"


# =============================================================================
# Linting - TypeScript
# =============================================================================

[tasks."typescript:typecheck"]
run = "bun x tsc --noEmit"
description = "Run TypeScript type checking"

[tasks."biome:lint:nofix"]
run = "biome check"
description = "Lint TypeScript files"

[tasks."biome:lint:fix"]
run = "biome check --fix"
description = "Lint and fix TypeScript files"

# =============================================================================
# Linting - Markdown
# =============================================================================

[tasks."markdown:lint:nofix"]
run = "markdownlint-cli2 '**/*.md'"
description = "Lint Markdown files"

[tasks."markdown:lint:fix"]
run = "markdownlint-cli2 '**/*.md' --fix"
description = "Lint and fix Markdown files"

# =============================================================================
# Linting - TOML
# =============================================================================

[tasks."toml:lint:nofix"]
run = "taplo format --check && taplo lint"
description = "Check TOML formatting and validate"

[tasks."toml:lint:fix"]
run = "taplo format"
description = "Format TOML files"


# =============================================================================
# Linting - JSON
# =============================================================================

[tasks."json:lint:nofix"]
run = "biome check"
description = "Lint JSON files"

[tasks."json:lint:fix"]
run = "biome check --fix"
description = "Lint and fix JSON files"


# =============================================================================
# Comprehensive Linting
# =============================================================================

[tasks."lint:all:nofix"]
depends = [
  "typescript:typecheck",
  "typescript:lint:nofix",
  "markdown:lint:nofix",
  "toml:lint:nofix",
  "json:lint:nofix",
]
description = "Run all linters (check only, no fixes)"
run = "echo '✅ All linting checks passed!'"

[tasks."lint:all:fix"]
depends = [
  "typescript:typecheck",
  "typescript:lint:fix",
  "markdown:lint:fix",
  "toml:lint:fix",
  "json:lint:fix",
]
description = "Run all linters with fixes"
run = "echo '✅ All linting checks passed!'"

# =============================================================================
# Testing
# =============================================================================

[tasks."test:unit"]
run = "bun test tests/unit/"
description = "Run unit tests (fast)"

[tasks."test:integration"]
run = "bun test tests/integration/"
description = "Run integration tests (slow)"

[tasks."test:full"]
run = "bun test"
description = "Run full test suite"

[tasks."test:coverage"]
run = "bun test --coverage"
description = "Generate test coverage report"

[tasks."test:ci"]
run = "bun test --reporter=verbose"
description = "Run test suite in CI mode"


# =============================================================================
# Schema Generation
# =============================================================================

[tasks.generate-schemas]
run = "bun run scripts/generate-json-schemas.ts"
description = "Generate JSON schemas from Zod"

[tasks.validate-schemas]
run = "bun run scripts/validate-schemas.ts"
description = "Validate JSON schemas against examples"

# =============================================================================
# Quality Gates
# =============================================================================

[tasks.quality-check]
depends = ["lint:all:nofix", "test", "generate-schemas", "validate-schemas"]
description = "Run all quality checks (lint, test, schemas)"
run = "echo '✨ All quality checks passed! Ready for commit.'"

# =============================================================================
# Utilities
# =============================================================================

[tasks.clean]
run = """
rm -rf dist coverage node_modules bun.lockb && \
echo '✅ Build artifacts cleaned!'
"""
description = "Clean all build artifacts"

[tasks.doctoc]
run = "bunx doctoc --notitle --stdout"
description = "Generate table of contents for markdown"
